
FIND_LIBRARY( QCA_LIBRARY QCA )

IF (WIN32)
	GET_FILENAME_COMPONENT(QCA_PATH ${QCA_LIBRARY} PATH)
	MESSAGE(${QCA_PATH})
	INCLUDE_DIRECTORIES(
		${QCA_PATH}/../include/QtCrypto/
	)

ENDIF (WIN32)
