
IF (APPLE)
	FIND_LIBRARY( TELLDUSCORE_LIBRARY TelldusCore )
	
	INCLUDE_DIRECTORIES(
		${TELLDUSCORE_LIBRARY}/Headers
	)
	
ELSEIF (WIN32)
	SET(TELLDUSCORE_LIBRARY ${LIBRARY_OUTPUT_PATH}/${CMAKE_CFG_INTDIR}/TelldusCore.lib)
	INCLUDE_DIRECTORIES( ${TELLDUSCORE_INCLUDE_DIR} )
	
ELSE (APPLE)
	FIND_LIBRARY( TELLDUSCORE_LIBRARY telldus-core )
	
	
ENDIF(APPLE)


